@echo off
REM Frontend Test Automation Script for Vibe Coding (Windows)
REM This script runs automated tests before completing work

setlocal enabledelayedexpansion

echo.
echo ================================
echo Frontend Pre-Deployment Tests
echo ================================
echo.

REM Create reports directory
if not exist "playwright-reports" mkdir playwright-reports

REM Step 1: TypeScript compilation check
echo [1/5] Checking TypeScript compilation...
call npm run build >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] TypeScript compilation failed
    call npm run build
    exit /b 1
)
echo [OK] TypeScript compilation successful
echo.

REM Step 2: Start dev server in background
echo [2/5] Starting development server...
start /b cmd /c "npm run dev > playwright-reports\server.log 2>&1"

REM Wait for server to be ready
echo Waiting for server to start...
set /a timeout=60
set /a counter=0

:waitloop
curl -s http://localhost:3000 >nul 2>&1
if %errorlevel% equ 0 goto serverready
timeout /t 1 /nobreak >nul
set /a counter+=1
if %counter% geq %timeout% (
    echo [ERROR] Server failed to start within %timeout% seconds
    taskkill /f /im node.exe >nul 2>&1
    exit /b 1
)
goto waitloop

:serverready
echo [OK] Development server is running
echo.

REM Step 3: Run Playwright tests
echo [3/5] Running Playwright browser tests...

REM Create a test script
(
echo const errors = [];
echo const warnings = [];
echo.
echo console.error = ^(...args^) =^> {
echo     errors.push^(args.join^(' '^)^);
echo };
echo.
echo console.warn = ^(...args^) =^> {
echo     warnings.push^(args.join^(' '^)^);
echo };
echo.
echo setTimeout^(^(^) =^> {
echo     console.log^('TEST_RESULTS:', JSON.stringify^({
echo         errors,
echo         warnings,
echo         url: window.location.href,
echo         title: document.title,
echo         readyState: document.readyState
echo     }^)^);
echo }, 3000^);
) > playwright-reports\test-console-errors.js

REM Run Playwright
npx @playwright/mcp@latest --browser chrome --headless --timeout-navigation 30000 --init-script playwright-reports\test-console-errors.js --output-dir playwright-reports > playwright-reports\test-output.log 2>&1

echo [OK] Browser tests completed
echo.

REM Step 4: Check for errors
echo [4/5] Analyzing test results...
findstr /C:"TEST_RESULTS" playwright-reports\test-output.log >nul
if %errorlevel% equ 0 (
    echo [OK] Test results captured
    
    REM Check for errors
    findstr /C:"""errors"":[]" playwright-reports\test-output.log >nul
    if %errorlevel% equ 0 (
        echo [OK] No console errors detected
    ) else (
        echo [WARNING] Console errors detected - check test-output.log
    )
) else (
    echo [WARNING] Could not extract test results
)
echo.

REM Step 5: Cleanup
echo [5/5] Cleaning up...
taskkill /f /im node.exe >nul 2>&1
echo [OK] Cleanup complete
echo.

REM Generate report
echo Generating test report...
(
echo # Frontend Test Report
echo **Date:** %date% %time%
echo **Project:** FlowCraft N8N Automation
echo.
echo ## Test Results
echo.
echo ### TypeScript Compilation
echo - Status: OK
echo.
echo ### Development Server
echo - Status: Started successfully
echo - URL: http://localhost:3000
echo.
echo ### Browser Tests
echo - Browser: Chrome ^(Headless^)
echo - Viewport: 1280x720
echo.
echo ### Console Output
echo See `test-output.log` for full details.
echo.
echo ### Artifacts
echo - Trace: Available in playwright-reports/
echo - Screenshots: Available in playwright-reports/
echo.
echo ---
echo Generated by automated testing pipeline
) > playwright-reports\test-report.md

echo [OK] Report generated: playwright-reports\test-report.md
echo.
echo ================================
echo All frontend tests completed!
echo ================================
echo.

exit /b 0
